name: recipe_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  go_router: ^13.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  permission_handler: ^11.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.2.1
  lottie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/asian.jpg
    - assets/burger.jpg
    - assets/desserts.jpg
    - assets/italian.jpg
    - assets/mexican.jpg
    - assets/pizza.jpg
    - assets/restaurant.jpg
    - assets/snacks.jpg
    - assets/soup.jpg
    - assets/spaghetti.jpg
    - assets/taco_salad.jpg
